services:
  - type: web
    name: lexiforge-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLAUDE_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: CORS_ORIGIN
        fromService:
          type: web
          name: lexiforge-frontend
          property: url
    autoDeploy: true

  - type: web
    name: lexiforge-frontend
    env: static
    region: oregon
    plan: starter
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: lexiforge-backend
          property: url
    autoDeploy: true

